The following set of changes include the updating of the README file to reflect what this action is about and its usage.
The addition of a code of conduct and contribution file was added for
developers that would be interested in getting involved with this
project.

Updated the release script such that a user can just include different
information on the command line instead of interactively.

Updated the package information to be inline with this action
implementation.

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -44,6 +44,44 @@ BOLD_PURPLE='\033[1;35m'
 BOLD_UNDERLINED='\033[1;4m'
 BOLD='\033[1m'
 
+function usage {
+	if ! test -z "$1"; then
+		status = $1
+	else
+		status = 0
+	fi
+	echo "usage: $0 -r <git_remote_id>"
+	echo "	-r <git_remote_id>, the git remote identification, default origin"
+	echo "	-v <version_tag,    use the passed version tag, using format vX.X.X"
+	echo "	-c,                 check that the version field is the same within package.json"
+	echo "	-h,                 print this message and exit"
+        echo ""
+        echo "This script can be used to create the required release tags and/or the release branch."
+        echo "It can determine if the required release branch was created and will also determine if"
+        echo "the provided version string conforms with the expected semantic version format."
+        echo ""
+	exit ${status}
+}
+
+check_version=false
+
+while getopts "hc:rv" o; do
+	case "${o}" in
+		# git remote identifier is not set to origin by default
+		r)	git_remote=${OPTARG}
+	                ;;
+		# use the passed version for this distribtion
+		v)	new_tag=${OPTARG}
+			;;
+		# check that the new tag is also assigned in the package.json file
+		c)  check_version=true
+			;;
+		# print help and exit with the passed status
+		h)	usage 0
+			;;
+	esac
+done
+
 # 1. Retrieve the latest release tag
 if ! latest_tag=$(git describe --abbrev=0 --match="$semver_tag_glob"); then
 	# There are no existing release tags
@@ -54,8 +92,10 @@ fi
 # 2. Display the latest release tag
 echo -e "The latest release tag is: ${BOLD_BLUE}${latest_tag}${OFF}"
 
+if test -z "${new_tag}"; then
 # 3. Prompt the user for a new release tag
 read -r -p 'Enter a new release tag (vX.X.X format): ' new_tag
+fi
 
 # 4. Validate the new release tag
 if echo "$new_tag" | grep -q -E "$semver_tag_regex"; then
@@ -67,9 +107,21 @@ else
 	exit 1
 fi
 
+if ${check_version}; then
+	# automatically check that the package.json version field was properly set
+	if grep "\"version\"" package.json | grep ${new_tag} > /dev/nul; then
+		# Package.json version field is not up to date
+		echo -e "Please update the package.json version to ${BOLD_PURPLE}$new_tag${OFF} and commit your changes"
+		exit 1
+	fi
+
+else
+
 # 5. Remind user to update the version field in package.json
 echo -e -n "Make sure the version field in package.json is ${BOLD_BLUE}$new_tag${OFF}. Yes? [Y/${BOLD_UNDERLINED}n${OFF}] "
 read -r YN
+
+fi
 
 if [[ ! ($YN == "y" || $YN == "Y") ]]; then
 	# Package.json version field is not up to date
